equipo(realmadrid).
equipo(realmadrid).
equipo(atletico).
equipo(zaragoza).
equipo(barsa).
equipo(atletico).
equipo(realmadrid).
equipo(barsa).
equipo(atletico).

jugador(messi).
jugador(alves).
jugador(alves).
jugador(ronaldo).
jugador(costa).
jugador(benzema).
jugador(courtois).
jugador(ronaldo).
jugador(courtois).
jugador(costa).
jugador(ronaldo).
jugador(courtois).
